services:
    Ecommerce:
        image: postgres:16
        restart: always
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
